# Generated by Django 4.0.1 on 2022-01-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='social_insta',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
