# Generated by Django 4.0.1 on 2022-01-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_about_social_insta'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
